// Code generated by "stringer -type Seed seed.go"; DO NOT EDIT.

package card

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Coin-0]
	_ = x[Cup-1]
	_ = x[Sword-2]
	_ = x[Cudgel-3]
}

const _Seed_name = "CoinCupSwordCudgel"

var _Seed_index = [...]uint8{0, 4, 7, 12, 18}

func (i Seed) String() string {
	if i >= Seed(len(_Seed_index)-1) {
		return "Seed(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Seed_name[_Seed_index[i]:_Seed_index[i+1]]
}
